### ISSUE TITLE
conda-forge build?

### ISSUE THREAD

**Issue by gschramm** [grantjenks/python-runstats#39]
What about adding runstats also to conda-forge?
I could help to create the build recipe, if you are interested.

The auto-generated `grayskull` recipe which could be used as 
a starting point looks like this:

```
{% set name = "runstats" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/runstats-{{ version }}.tar.gz
  sha256: 0f9a5e6cc9938bbac3474b17727ffc29fbf5895f33e55ce8843341e0821e77c2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - cython
    - tox
    - pip
  run:
    - python >=3.6

test:
  imports:
    - runstats
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.grantjenks.com/docs/runstats/
  summary: Compute statistics and regression in one pass
  dev_url: https://github.com/grantjenks/python-runstats
  license: Apache-2.0
  license_file: LICENSE
```
